#!/usr/bin/env bash
#
# Generalized caller SHA-bumper for the reusable workflows in this repo.
#
# When a reusable workflow (e.g. cursor-review.yml or agents-md-integrity.yml)
# is updated on main, this opens a SHA-bump PR in every repo that pins a caller
# against it. It is fleet-agnostic: the thin workflow entrypoints
# (bump-cursor-review-callers.yml, bump-agents-md-callers.yml,
# bump-pr-size-callers.yml) invoke it with a different caller list, human tag,
# and reusable-workflow filename. There is ONE implementation so the fleets
# cannot drift apart (a forked copy is how other shared machinery in the org
# has rotted); the entrypoints differ only in their path-filter triggers and
# the parameters below.
#
# This repo is PUBLIC (both the workflow files and the Actions run logs are
# publicly viewable) and most callers are private, so caller names must never
# appear in a committed file or in the logs. Each caller list lives in a
# repo-level Actions variable (config, not a credential — a variable, not a
# secret) as a JSON array of {"repo","file","label","wire_bot"} objects, and
# every repo name is `::add-mask::`ed out of the run logs before it is ever
# echoed.
#
# The roster is FETCHED HERE at run time rather than handed in through the
# entrypoint's step `env:` block (BE-6482). Actions prints a step's env block into
# the run log BEFORE the step runs, so an `env:`-passed roster appeared in this
# PUBLIC repo's world-readable logs ahead of the `::add-mask::` loop below — the
# masking could not win a race it started after. Reading the variable inside the
# script puts the fetch, the validation and the mask in an order the log cannot
# get in front of.
#
# Required environment:
#   GH_TOKEN       Token with contents:write + pull-requests:write on the callers
#                  (the Cloud Code Bot app token generated by the entrypoint).
#                  This is the WRITE token and stays downscoped; it is used for
#                  the roster read only as a fallback when VAR_TOKEN is unset.
#   NEW_SHA        The github-workflows commit to pin callers to (github.sha).
#   VAR_NAME       Name of the fleet's Actions variable. The roster is READ from
#                  it at run time (and it names the variable in error messages).
#   GITHUB_REPOSITORY  Owner/name of THIS repo, for that read (Actions sets it).
#   TAG            Human tag for branch/commit/PR text (e.g. "cursor-review").
#   WORKFLOW_FILE  Reusable workflow filename referenced in the PR body.
# Optional:
#   VAR_TOKEN      Token used for the roster read ALONE. The entrypoints mint a
#                  second app token for it, scoped to THIS repo only and with no
#                  `permission-*` downscoping, because the app-permissions API
#                  schema (the installation-token request body) has no `variables`
#                  key to ask for — only an un-downscoped token carries the App's
#                  "Variables: read" grant (BE-6477). Splitting it off is what
#                  keeps GH_TOKEN, which writes to every caller repo in the fleet,
#                  on its narrow trio. Falls back to GH_TOKEN when unset.
#   CALLERS_JSON   OVERRIDE for the runtime fetch — the caller list, verbatim.
#                  Used by the test suite and available for an emergency manual
#                  run; the entrypoints deliberately do NOT set it. Set-but-EMPTY
#                  is an override too (it means "empty roster", handled by
#                  ALLOW_EMPTY below); only a genuinely UNSET value fetches.
#   ALLOW_EMPTY      "true" → an empty caller list is a clean no-op (a fleet that
#                    is seeded empty and grows). Default "false" → an empty/missing
#                    list is a hard error (a fleet that always has callers must
#                    never silently no-op — that would leave every caller un-bumped
#                    without anyone noticing).
#   WIRE_BOT_SCRIPT  Path to a helper that reads a caller's YAML on stdin and
#                    writes it back wired for some extra identity/config, idempotently
#                    (BE-1814's .github/cursor-review/wire-bot-identity.py). Only
#                    consulted for an entry whose `wire_bot` field is true; unset
#                    (the agents-md-integrity entrypoint never sets it) means no
#                    fleet here uses wiring, so a stray `wire_bot: true` in that
#                    fleet's variable is a harmless no-op with a warning, not a
#                    failure — this keeps the script itself cursor-review-agnostic.

# NOTE: deliberately no `set -e`. Each caller is bumped independently in
# bump_one(); a failure there returns non-zero and is downgraded to a per-repo
# warning so one bad repo cannot abort the whole fan-out. We still fail the job
# at the end if any repo failed.
set -uo pipefail

: "${NEW_SHA:?NEW_SHA is required}"
: "${VAR_NAME:?VAR_NAME is required}"
: "${TAG:?TAG is required}"
: "${WORKFLOW_FILE:?WORKFLOW_FILE is required}"
ALLOW_EMPTY="${ALLOW_EMPTY:-false}"
WIRE_BOT_SCRIPT="${WIRE_BOT_SCRIPT-}"

# Load the roster. Normally it is READ HERE, from this repo's own Actions
# variable named by VAR_NAME — see the header for why it is not passed in
# through the step's `env:`.
#
# The test is `+x`, i.e. "is CALLERS_JSON set AT ALL", NOT `-z "$CALLERS_JSON"`.
# A set-but-EMPTY override must keep meaning "the roster is empty" and fall
# through to the ALLOW_EMPTY handling below — the suite drives the empty-variable
# hard-fail that way, and more importantly an emergency manual run that passes
# `CALLERS_JSON=''` must not silently reach past it and bump the LIVE roster.
if [[ -z "${CALLERS_JSON+x}" ]]; then
  if [[ -z "${GITHUB_REPOSITORY:-}" ]]; then
    echo "::error::GITHUB_REPOSITORY is unset, so the ${VAR_NAME} Actions variable cannot be read. Run this from Actions, or pass the roster explicitly in CALLERS_JSON."
    exit 1
  fi
  # `gh api`, NOT `gh variable get`: only the REST path surfaces the HTTP status,
  # and telling 404 from 403 is the whole point here. `gh variable get` exits 1
  # for both, so an absent variable (a legitimate empty roster for a seeded-empty
  # fleet) would be indistinguishable from a token that cannot read variables at
  # all — one is a clean no-op, the other needs an operator to grant a permission.
  #
  # The read runs under VAR_TOKEN when the entrypoint mints one: a SECOND app
  # token, scoped to THIS repo alone (`repositories: github-workflows`) and left
  # un-downscoped so it carries the App's "Variables: read" grant. That is what
  # lets GH_TOKEN — the token that actually WRITES across every caller repo —
  # keep its narrow `permission-contents`/`pull-requests`/`issues` trio, instead
  # of the whole fleet's write token being widened to full installation
  # permissions just to enable one variable read (BE-6482 review). Falling back
  # to GH_TOKEN keeps a manual/legacy invocation working.
  VAR_ERR=$(mktemp) || {
    echo "::error::Could not create a temp file for the ${VAR_NAME} read's stderr (mktemp failed)."
    exit 1
  }
  trap 'rm -f "$VAR_ERR"' EXIT
  VAR_READ_TOKEN="${VAR_TOKEN:-${GH_TOKEN:-}}"

  # Reduce an API error body to ONE safe log line: the REASON only, never the
  # value (the value goes to stdout; this reads stderr). The run logs of this
  # public repo are a workflow-command sink, so a `\r::` in an error body could
  # otherwise inject a command of its own. The `::` squash LOOPS to a fixpoint —
  # a single `s|::|:|g` pass is not one, since `::::x::::` collapses straight
  # back into `::x::`.
  sanitize_api_error() {
    local s
    s=$(tr -d '\r' <"$1" | tr '\n' ' ' | sed -E 's|[[:space:]]+| |g; s|^ ||; s| $||')
    while [[ "$s" == *::* ]]; do s="${s//::/:}"; done
    printf '%s' "$s"
  }

  # A non-404 failure of the repo-scope read. Never recoverable here, so it ends
  # the run — but with the RIGHT remediation: 403 is not only "missing grant".
  var_read_die() {
    local reason; reason=$(sanitize_api_error "$VAR_ERR")
    if grep -qiE 'rate limit|secondary rate|abuse detection' "$VAR_ERR"; then
      echo "::error::Could not read the ${VAR_NAME} Actions variable — GitHub throttled the request (retry later, no permission change needed): ${reason}"
    elif grep -qi 'HTTP 403' "$VAR_ERR"; then
      # Overwhelmingly the missing grant, so lead with it — but a 403 is also how
      # GitHub answers an IP-allow-list / SAML-enforcement / suspended-installation
      # denial, so carry the sanitized reason rather than asserting the cause.
      echo "::error::App token cannot read Actions variables — grant the Cloud Code Bot App repository permission 'Variables: read' and approve it on the Comfy-Org installation (BE-6477). A 403 can also mean an IP allow-list, SAML enforcement or a suspended installation — API said: ${reason}"
    else
      echo "::error::Could not read the ${VAR_NAME} Actions variable: ${reason}"
    fi
    exit 1
  }

  if ! CALLERS_JSON=$(GH_TOKEN="$VAR_READ_TOKEN" gh api "repos/${GITHUB_REPOSITORY}/actions/variables/${VAR_NAME}" --jq '.value' 2>"$VAR_ERR"); then
    grep -qi 'HTTP 404' "$VAR_ERR" || var_read_die
    # A repo-scope 404 is not yet "no roster". The `${{ vars.* }}` binding this
    # read replaced ALSO resolved ORG-level variables (repo-level winning on a
    # name clash), so try the org before concluding the roster is empty —
    # otherwise a fleet whose roster is defined org-wide silently becomes an
    # empty one. Best-effort: this repo's rosters are repo-level by convention
    # and the App may hold no org-level Variables grant at all, so a FAILED org
    # probe must not turn today's clean no-op into a hard failure.
    VAR_OWNER="${GITHUB_REPOSITORY%%/*}"
    if ! CALLERS_JSON=$(GH_TOKEN="$VAR_READ_TOKEN" gh api "orgs/${VAR_OWNER}/actions/variables/${VAR_NAME}" --jq '.value' 2>"$VAR_ERR"); then
      # Genuinely absent at BOTH scopes == an empty roster, spelled the same way
      # an empty variable is, so the ALLOW_EMPTY block below keeps its EXACT
      # semantics: a clean no-op for a fleet seeded empty, and the loud
      # clobber-detecting error for a fleet that must always have callers
      # (auto-label, cursor-review, detect-unreviewed-merge).
      #
      # Say so OUT LOUD either way. A 404 is also what GitHub returns when the
      # token cannot see the repository at all — App uninstalled, repo-selection
      # drift, a renamed repo, a VAR_NAME typo in some future fleet — and for the
      # ALLOW_EMPTY=true fleets that would otherwise be a completely silent
      # "nothing to do" while the whole fleet quietly stops being bumped, which
      # is the exact pin rot this bumper exists to prevent.
      echo "::warning::No ${VAR_NAME} Actions variable found on ${GITHUB_REPOSITORY} or on org ${VAR_OWNER} (HTTP 404 at the repo scope; org probe: $(sanitize_api_error "$VAR_ERR")) — treating the roster as EMPTY. If this fleet is supposed to have callers, the variable is missing or misnamed, or the token cannot see this repository."
      CALLERS_JSON=""
    fi
  fi
  rm -f "$VAR_ERR"
  trap - EXIT
fi

SHORT="${NEW_SHA:0:7}"
# Stable branch per (repo, TAG) — deliberately NOT SHA-stamped. A fixed head
# branch is what lets a subsequent bump reuse (and update in place) the one open
# bump PR instead of opening a fresh PR on every SHA (BE-3882). The SHA lives in
# the commit/title/body, not the branch name.
BRANCH="ci/bump-${TAG}"

# The two forms a caller uses to pin THIS repo, written as regex prefixes that
# end exactly where the ref begins. They live here, together, because the
# rewrite below and the post-rewrite assertion that guards it must never drift
# apart: whatever the rewrite is expected to move, the assertion re-reads.
#   1. the `uses:` pin — `Comfy-Org/github-workflows/<path>@<ref>`
#   2. the input pin  — `workflows_ref: <ref>` (optionally quoted), which loads
#      this repo's prompts/briefs/scripts at run time
# INPUT_PIN_RE is applied `^`-anchored (see the rewrite), i.e. only where
# `workflows_ref:` is a block-mapping KEY. That is what keeps the rewrite off a
# prose comment that merely mentions the input — `# workflows_ref: keep in sync
# with uses:` must not come back with a SHA spliced into the middle of the
# sentence. The assertion below is deliberately NOT anchored that way, so the
# one shape this misses (flow style, `with: {workflows_ref: v1}`) fails the repo
# loudly instead of silently half-bumping it.
#
# The repo name is spelled case-INSENSITIVELY because GitHub resolves a `uses:`
# owner/repo that way — a caller written `comfy-org/github-workflows/…@<old>` is
# calling THIS repo and must be bumped like any other. Missing it would be the
# worst kind of miss: rule 2 below is repo-agnostic, so the caller's
# `workflows_ref:` half would move while `uses:` stayed stale, and the assertion
# (which reuses this same regex to read `uses:` back) would not see the stale
# half either — shipping exactly the split bump this change exists to prevent.
# Character classes rather than a case-insensitive flag: sed's `I` and grep's
# `-i` are not portable/scopable the same way, and this regex is shared by both.
REPO_RE='[Cc][Oo][Mm][Ff][Yy]-[Oo][Rr][Gg]/[Gg][Ii][Tt][Hh][Uu][Bb]-[Ww][Oo][Rr][Kk][Ff][Ll][Oo][Ww][Ss]'
# The path segment is OPTIONAL but the delimiter after the repo name is NOT:
# what follows `github-workflows` must be the `/` that starts the path or the `@`
# that starts the ref. Without that, `[^@[:space:]]*` also swallows a SIBLING
# repo's name — `Comfy-Org/github-workflows-tools/action@v1` would be repinned to
# THIS repo's SHA, and because the assertion reuses this regex it would read the
# corrupted value back as NEW_SHA and stage it silently.
USES_PIN_RE="${REPO_RE}(/[^@[:space:]]*)?@"
INPUT_PIN_RE='[[:space:]]*workflows_ref:[[:space:]]*['\''"]?'
# The assertion's reader for the input pin. Deliberately looser than
# INPUT_PIN_RE's `^`-anchored use — it also catches flow style
# (`with: {workflows_ref: v1}`), which the rewrite cannot move — but it still
# needs a LEFT boundary. Unanchored, `workflows_ref:` matches inside a longer key
# like `upstream_workflows_ref: v1`, whose value rule 2 correctly leaves alone;
# the assertion would then read that value as a stale github-workflows pin and
# hard-fail an otherwise-clean repo on every run. The boundary is a plain
# character class, not `(^|…)`: `^` inside a group is a GNU extension, and the
# assertion pads every line with a leading space first (see below) so a key at
# column 0 is covered by the same class.
INPUT_KEY_RE='[[:space:],{]workflows_ref:'
# A LITERAL ref: a full sha, a short sha, or a tag (`v1`). Deliberately excludes
# quotes, `#` and `$ { } ( )` so a closing quote or a trailing comment is never
# swallowed, and a GitHub expression (`workflows_ref: ${{ inputs.workflows_ref }}`)
# is never half-rewritten into a broken value — an expression matches nothing
# here, is left untouched, and is then caught by the assertion, which fails the
# repo rather than shipping a caller whose two pins disagree.
# shellcheck disable=SC2016  # `$ { }` here are regex literals, not an expansion
REF_RE='[^[:space:]'\''"#$(){}]+'

STRIPPED="${CALLERS_JSON//[[:space:]]/}"

# Empty handling is fleet-specific. A fleet seeded empty (ALLOW_EMPTY=true)
# treats an empty/absent list as an expected clean no-op — its per-repo caller
# tickets add entries as callers land. Every other fleet keeps the original
# hard-fail so a silent no-op dispatcher (which would leave every caller
# un-bumped) is impossible.
if [[ "$ALLOW_EMPTY" == "true" ]] && { [[ -z "$STRIPPED" ]] || [[ "$STRIPPED" == "[]" ]]; }; then
  echo "${VAR_NAME} has no callers yet — nothing to bump for ${TAG}."
  exit 0
fi

# Load the caller list. Hard-fail loudly on a missing/empty/invalid value.
if [[ -z "$STRIPPED" ]]; then
  echo "::error::${VAR_NAME} variable is missing or empty. Seed it with the caller list — see this workflow's header comment for the update flow."
  exit 1
fi
if ! jq -e 'type == "array" and length > 0 and all(.[]; (.repo | type == "string" and . != "") and (.file | type == "string" and . != "") and (.wire_bot == null or (.wire_bot | type == "boolean")))' <<<"$CALLERS_JSON" >/dev/null 2>&1; then
  echo "::error::${VAR_NAME} is not a non-empty JSON array of {repo,file,label,wire_bot} objects (each needing a non-empty repo and file, and a boolean wire_bot if present). Fix the variable — see the workflow header."
  exit 1
fi

# Parse the JSON into repo|file|label|wire_bot tuples, and mask every repo name
# in the (publicly viewable) run logs BEFORE the loop that echoes it, so all
# per-repo output shows *** instead of a private repo name.
#
# INVARIANT (BE-6482): this loop is the FIRST place the roster's repo names are
# used for anything, and nothing above it may log the roster — not the fetch, not
# the empty/shape validation, not an error path. Everything before this point
# either handles the value silently or reports only a REASON, and the order
# fetch → validate → mask must stay that way. The whole reason the roster is read
# here instead of arriving through the step's `env:` is that Actions printed the
# env block before this loop could run; adding an echo of the value above it
# re-opens exactly that hole, in a public log, irreversibly. jq's `//` treats
# both `false` and `null` as falsy, so an absent/false/null wire_bot all print
# the empty string here — exactly the "not flagged" case.
CALLERS=()
while IFS= read -r ENTRY; do
  echo "::add-mask::${ENTRY%%|*}"
  CALLERS+=("$ENTRY")
done < <(jq -r '.[] | "\(.repo)|\(.file)|\(.label // "")|\(.wire_bot // "")"' <<<"$CALLERS_JSON")

if (( ${#CALLERS[@]} == 0 )); then
  echo "::error::${VAR_NAME} parsed to zero callers — refusing to run a no-op dispatcher."
  exit 1
fi

# Bump ONE caller repo, committing EVERY file that repo pins onto a single
# stable bump branch. Called once per repo with that repo's entries, so a repo
# listed more than once in the caller variable (a monorepo pinning the reusable
# workflow from several workflow files) lands ALL its files on ONE branch/PR.
# Every external call is guarded, so a bad repo returns non-zero here (caught by
# the loop) instead of killing the run. A repo whose files are all missing or
# already pinned commits nothing and is a successful skip (`return 0`).
#
# Grouping by repo is load-bearing: all of a repo's files are built into ONE
# atomic commit (Git Data API) off the default-branch tip and the bump branch is
# moved to it in a single step, so the PR either bumps every file or none — never
# a partial-yet-mergeable bump. The earlier per-file Contents PUT loop committed
# files one at a time with no rollback, so a mid-sequence failure left the
# earlier files already committed on the branch (BE-3902); and before that a
# per-ENTRY branch reset discarded earlier commits so only the last file shipped
# (BE-3896). One commit for the whole repo closes both.
bump_repo() {
  local REPO="$1"; shift   # remaining args: this repo's "repo|file|label" entries

  local DEFAULT_BRANCH
  DEFAULT_BRANCH=$(gh api "repos/${REPO}" --jq '.default_branch') || {
    echo "::warning::${REPO}: cannot read repo metadata — skipping"
    return 1
  }

  # Resolve the default-branch tip ONCE, up front. Every Pass-1 fetch is pinned
  # to this immutable SHA (not the mutable `?ref=<branch>`), and Pass 2 uses the
  # same commit as the new commit's parent AND (via its resolved tree) as the
  # tree's `base_tree` — so the whole bump is built against one consistent
  # snapshot of the caller repo, never a moving tip. Reading the tip is a GET (no
  # branch churn), so it is safe before the all-skip early return.
  local MAIN_SHA
  MAIN_SHA=$(gh api "repos/${REPO}/git/refs/heads/${DEFAULT_BRANCH}" --jq '.object.sha') || {
    echo "::warning::${REPO}: cannot read ${DEFAULT_BRANCH} ref — skipping"
    return 1
  }

  # Pass 1 — stage every file that actually needs a bump WITHOUT writing
  # anything yet. This keeps the reset/commit path off entirely for a repo whose
  # files are all missing or already pinned (the old per-entry skips), so it
  # never resets a branch or opens a PR it doesn't need.
  local -a PEND_FILE=() PEND_CONTENT=() LABELS=()
  local WIRING_ADDED_ANY=""
  local ENTRY FILE LABEL WIRE_BOT FILE_ENC CURRENT OLD_CONTENT NEW_CONTENT
  for ENTRY in "$@"; do
    FILE=$(cut -d'|' -f2 <<<"$ENTRY")
    LABEL=$(cut -d'|' -f3 <<<"$ENTRY")
    WIRE_BOT=$(cut -d'|' -f4 <<<"$ENTRY")
    FILE_ENC="${FILE//\//%2F}"

    # De-duplicate by file: a repo listed twice for the SAME path (a structurally
    # valid config) must stage that file ONCE. A second PUT carrying the same
    # pre-bump blob `sha` would 409 — the first PUT already moved the blob — and
    # fail the whole repo even though the file was actually bumped. Fold the
    # duplicate entry's label into the set (it still applies to the one PR) but
    # do not re-stage the file.
    local SEEN_FILE=0 P
    for P in ${PEND_FILE[@]+"${PEND_FILE[@]}"}; do
      [[ "$P" == "$FILE" ]] && { SEEN_FILE=1; break; }
    done
    if (( SEEN_FILE )); then
      [[ -n "$LABEL" ]] && LABELS+=("$LABEL")
      continue
    fi

    # Fetch current file, pinned to the resolved tip. Distinguish a genuine 404
    # (this file is actually absent → an expected per-file skip) from ANY other
    # failure (auth, rate limit, 5xx, network). Treating a transient error as
    # "not found" and continuing would open a PR that silently OMITS this file
    # while the job still reports success — the partial-bump class this refactor
    # exists to kill (BE-3896). So a non-404 failure fails the whole repo.
    local ERRFILE RC
    ERRFILE=$(mktemp)
    CURRENT=$(gh api "repos/${REPO}/contents/${FILE_ENC}?ref=${MAIN_SHA}" 2>"$ERRFILE"); RC=$?
    if (( RC != 0 )); then
      if grep -qi 'HTTP 404' "$ERRFILE"; then
        echo "::warning::${REPO}: ${FILE} not found — skipping"
        rm -f "$ERRFILE"
        continue
      fi
      echo "::warning::${REPO}: ${FILE} fetch failed (HTTP error, not 404) — failing repo to avoid a partial bump"
      rm -f "$ERRFILE"
      return 1
    fi
    rm -f "$ERRFILE"

    OLD_CONTENT=$(jq -r '.content' <<<"$CURRENT" | base64 -d)

    # Which github-workflows reusables does this file actually CALL? Taken from
    # `uses:` lines only (`^[^#]*uses:` keeps a commented-out `# uses:` out), so a
    # prose comment or a docs URL that merely NAMES a sibling workflow cannot make
    # a single-reusable caller look multi-reusable — that would wrongly trip the
    # attribution guard below and leave the caller's marker stale, i.e. re-create
    # the very BE-4523 bug. Empty means we could not identify one (an unusual
    # spelling): treated as "not provably ours", which only ever costs the
    # marker refresh, never a pin bump.
    local GW_USES
    GW_USES=$(grep -oE '^[^#]*uses:[[:space:]]*[^[:space:]]*github-workflows/\.github/workflows/[A-Za-z0-9._-]+\.ya?ml' <<<"$OLD_CONTENT" \
      | sed -E 's|.*/||' | sort -u) || true
    # Provably ours alone → safe to rewrite unattributed marker comments.
    # Provably NOT ours alone → this file also calls a SIBLING fleet's reusable.
    local GW_ONLY_OURS=0 GW_HAS_SIBLING=0
    if [[ -n "$GW_USES" ]]; then
      if [[ "$GW_USES" == "$WORKFLOW_FILE" ]]; then GW_ONLY_OURS=1; else GW_HAS_SIBLING=1; fi
    fi

    # Rewrite the github-workflows pin(s) to NEW_SHA and normalize the stale pin
    # comments.
    #
    # Rules 1-2 are anchored to the PIN TOKEN itself (BE-4662) —
    # `Comfy-Org/github-workflows…@<ref>` and `workflows_ref: <ref>` — NOT to
    # "any 40-hex on a line that mentions github-workflows or workflows_ref",
    # which is what this used to key on. Keying on the line was wrong in both
    # directions, and silently so:
    #   * UNDER-rewrite. A caller pins this repo TWICE — the `uses:` sha and the
    #     `workflows_ref:` input that loads the briefs/prompts/scripts at run
    #     time — and the halves must move in lock-step or a run executes one
    #     version's workflow against another version's assets. A `workflows_ref`
    #     pinned to a TAG (`v1`) or a short sha is not 40 hex, so it was left
    #     behind while `uses:` moved, and the content-equality check below still
    #     saw a difference — a green-looking bump PR on a split caller.
    #   * OVER-rewrite. An unrelated 40-hex value that merely shared such a line
    #     was clobbered to NEW_SHA.
    # Matching the ref by POSITION (right after the pin token) instead of by
    # 40-hex-ness fixes both at once: any literal ref shape is moved, and a
    # full-SHA pin of ANOTHER action (`actions/checkout@<sha>`, the org's
    # mandated practice) or a co-located digest is unreachable by both patterns.
    # Rule 2 is additionally `^`-anchored so it only fires where `workflows_ref:`
    # is a block-mapping key, never inside a prose comment that mentions it.
    #
    # In a file that also calls a SIBLING github-workflows reusable, rule 1 (the
    # `uses:` pin — token-anchored on repo name alone, not on WHICH reusable) is
    # additionally address-restricted to OUR reusable's path via SHA_ADDR: without
    # it, a caller pinning TWO github-workflows reusables would have BOTH `uses:`
    # lines bumped to this fleet's SHA — a cross-fleet stamp that silently points
    # the sibling caller at a commit its own fleet never shipped. Rules 4-6 (the
    # `# main @` comment, below) ride on the SAME address, since the annotation
    # belongs to whichever pin line it sits on. The tightening is inert for every
    # caller today (all 23 call exactly one github-workflows reusable, so the
    # address matches everywhere rule 1 would anyway); it exists so a caller that
    # starts calling two cannot be corrupted.
    #
    # Rule 2 (`workflows_ref:`) stays unaddressed in both cases: it is a `with:`
    # input carrying no workflow name, so telling OUR job's from a sibling job's
    # needs YAML block structure a line-wise sed does not have — and leaving ours
    # un-bumped (a `workflows_ref` disagreeing with its own `uses:` pin) is the
    # worse failure. Unreachable while no caller calls two reusables; if one ever
    # does, parse the YAML instead of extending this rule.
    local SHA_ADDR='github-workflows|workflows_ref'
    if (( GW_HAS_SIBLING )); then
      SHA_ADDR="github-workflows[^[:space:]]*${WORKFLOW_FILE//./\\.}|workflows_ref"
    fi
    #
    # The `# github-workflows#NN` legacy marker (and its already-converted
    # `main (<short>)` form) is deliberately NOT rewritten here — it names a SHA
    # but not WHICH reusable's pin it annotates (it can sit in prose ABOVE the
    # `uses:` line, outside any single pin's address), so it cannot be
    # address-scoped like the rules below. It is normalized after this rewrite,
    # gated on GW_ONLY_OURS (see below), instead of unconditionally here.
    #
    # Rules 4-6 normalize the `# main @ <sha>` comment (the groom callers' form),
    # because a comment that still names the OLD commit after the pin moved is
    # worse than no comment — it is a confident lie in the one file where the pin
    # is the whole point: `# main @ 29a81ca …` -> `# main @ <short> …`. Rule 4 (the
    # FULL-sha form) is load-bearing now that rules 1-2 no longer sweep every
    # 40-hex on the line: a deliberate `# main @ <40hex>` note used to be
    # corrected as collateral of the old broad substitution, and would otherwise
    # be left naming the old commit. Rules 5-6 handle the SHORT form and are
    # bounded to {7,12} hex, which only holds if the hex run ENDS there —
    # `[0-9a-f]{7,12}` alone is happy to match the first 12 characters of a longer
    # run, so on a 40-hex comment it would swap 12 hex for the 7-char SHORT and
    # leave the remaining 28 dangling, mangling the very full-form comment rule 4
    # just corrected. Requiring a non-hex character (rule 5) or end of line
    # (rule 6) after the run makes the match a whole token, so a 13+ hex run
    # matches neither. A hex-boundary assertion (`\b`, `[[:>:]]`) would be simpler
    # but spells differently in GNU and BSD sed; this is portable ERE.
    NEW_CONTENT=$(sed -E "
      /${SHA_ADDR}/ s|(${USES_PIN_RE})${REF_RE}|\1${NEW_SHA}|g
      s|^(${INPUT_PIN_RE})${REF_RE}|\1${NEW_SHA}|
      /${SHA_ADDR}/ s|# main @ [0-9a-f]{40}|# main @ ${NEW_SHA}|g
      /${SHA_ADDR}/ s|# main @ [0-9a-f]{7,12}([^0-9a-f])|# main @ ${SHORT}\1|g
      /${SHA_ADDR}/ s|# main @ [0-9a-f]{7,12}\$|# main @ ${SHORT}|g
    " <<<"$OLD_CONTENT")

    # Normalize the human-readable pin annotation so it never disagrees with the
    # pin above. Two spellings, both handled here:
    #   * the LEGACY `# github-workflows#NN` form (converted on first sight), and
    #   * the ALREADY-CONVERTED `github-workflows main (<short>)` form (BE-4523).
    # Only the legacy rule existed before, and it fires once — so after a caller
    # was migrated, every later bump advanced the real 40-hex pin and left the
    # annotation frozen at whatever it was on conversion day. Comfy-iOS shipped a
    # bump whose `uses:`/`workflows_ref` were current while both of its marker
    # comments still named a SHA the file no longer used, and it had to be
    # hand-fixed. The marker pattern is deliberately NOT anchored to `# ` so it
    # also catches the prose form callers put ABOVE the `uses:` line ("# Pinned
    # to github-workflows main (dc65b8b). …"), which is the same annotation and
    # goes stale the same way; `{7,40}` covers both the short and full-SHA
    # spellings. Re-running against an already-current marker rewrites it to
    # itself, so this stays a no-op for a converged caller (the already-pinned
    # clean-skip path still skips). A caller using some other comment form
    # (agents-md-integrity's `# v1`) matches neither rule and is untouched.
    #
    # Attribution guard: an annotation of these two forms names a SHA but not
    # WHICH reusable it annotates — and, appearing in prose above the pin as often
    # as beside it, it carries no line context to attribute it by either. So in a
    # file that calls several github-workflows reusables there is no honest way to
    # tell whose is whose, and rewriting them all would stamp this fleet's SHA
    # onto a sibling fleet's annotation. Rewrite only when the file is provably
    # ours alone; otherwise leave every annotation as found and say so. (No caller
    # does this today; the guard is why the new rule cannot regress one that starts
    # to.) The `# main @` form needs no guard here — it is bound to the pin line it
    # annotates and moved above, under the same address as the pin itself.
    if (( GW_ONLY_OURS )); then
      NEW_CONTENT=$(sed -E "s|# github-workflows#[0-9]+|# github-workflows main (${SHORT})|g; s|github-workflows main \([0-9a-f]{7,40}\)|github-workflows main (${SHORT})|g" <<<"$NEW_CONTENT")
    elif grep -qE '# github-workflows#[0-9]+|github-workflows main \([0-9a-f]{7,40}\)' <<<"$OLD_CONTENT"; then
      echo "::warning::${REPO}: ${FILE} does not call ${WORKFLOW_FILE} alone — leaving its github-workflows pin comments untouched"
    fi

    # Wire an extra identity/config into this file when its entry is flagged
    # (BE-1814's cloud-code-bot review identity is the first user). Idempotent —
    # an already-wired caller comes back unchanged — so this only adds the
    # wiring to callers that don't have it yet, alongside the SHA bump. Folded
    # into the SAME content-equality check below (not a separate "grep for the
    # wired marker" skip) so a wiring-only change on an already-SHA-current
    # caller still stages the file instead of being short-circuited.
    if [[ -n "$WIRE_BOT" ]]; then
      if [[ -z "$WIRE_BOT_SCRIPT" ]]; then
        echo "::warning::${REPO}: ${FILE} flagged wire_bot but WIRE_BOT_SCRIPT is unset — bumping SHA only"
      else
        local WIRED
        if WIRED=$(python3 "$WIRE_BOT_SCRIPT" <<<"$NEW_CONTENT") && [[ -n "$WIRED" ]]; then
          [[ "$WIRED" != "$NEW_CONTENT" ]] && WIRING_ADDED_ANY=1
          NEW_CONTENT="$WIRED"
        else
          echo "::warning::${REPO}: ${FILE} bot-identity wiring failed — bumping SHA only"
        fi
      fi
    fi

    # ASSERT that the rewrite actually moved EVERY github-workflows pin in this
    # file, before it can be staged (BE-4662). The patterns above are precise by
    # design, and precision cuts both ways: a pin form they do not know how to
    # move is silently left behind. So re-read the result with a DELIBERATELY
    # BROADER reader — any non-whitespace value sitting where a ref belongs — and
    # fail the repo if anything but NEW_SHA is still there. The gap between the
    # two (today: a `workflows_ref` fed by a `${{ … }}` expression, which is
    # deliberately never rewritten) then surfaces as a loud, named failure
    # instead of a green-looking PR that bumps `uses:` and leaves the assets ref
    # behind. A caller running one version's workflow against another version's
    # briefs is exactly the split this fleet exists to prevent, and — as with the
    # transient fetch error above — a partial bump is worse than no bump (BE-3896).
    #
    # Comments are not pins, so drop them before scanning: a prose note that
    # happens to say `workflows_ref:` must not fail an otherwise-clean repo. A
    # comment is stripped by YAML's OWN rule — a `#` preceded by whitespace (every
    # line is padded with a leading space first, so that also covers a `#` at
    # column 0, and gives INPUT_KEY_RE's boundary class a character to match at
    # line start) — NOT at the first `#` anywhere on the line. That distinction is
    # what keeps the assertion honest about a `#` INSIDE a value: REF_RE stops at
    # `#`, so `workflows_ref: 'feature#1'` is rewritten to `'<NEW_SHA>#1'`, and a
    # first-`#` strip would read back a bare NEW_SHA and accept that corrupted
    # value. Under YAML's rule the value survives intact, compares unequal, and
    # fails the repo — the loud outcome, as designed.
    local LIVE_CONTENT USES_SCAN STALE_PINS SAFE_PINS
    LIVE_CONTENT=$(sed -E 's|^| |; s|[[:space:]]#.*$||' <<<"$NEW_CONTENT")
    # The `uses:` pin scan is restricted to the same SHA_ADDR-eligible lines as
    # rule 1's rewrite above (a no-op restriction outside the sibling case): a
    # sibling reusable's `uses:` pin is deliberately left untouched by rule 1, so
    # scanning it here too would read its (unrelated, un-moved) ref as a stale
    # github-workflows pin and fail an otherwise-clean repo. The `workflows_ref:`
    # scan below stays unrestricted — rule 2 is unaddressed for the same reason.
    USES_SCAN=$(grep -E "$SHA_ADDR" <<<"$LIVE_CONTENT") || true
    STALE_PINS=$(
      {
        # A `uses:` ref cannot contain whitespace, so the token after `@` is the
        # whole ref. `workflows_ref` is a YAML scalar, so take the rest of the
        # line — that keeps an expression value readable in the warning instead
        # of truncating it to `${{`.
        grep -oE "${USES_PIN_RE}[^[:space:]]+" <<<"$USES_SCAN" | sed -E 's|^.*@||'
        grep -oE "${INPUT_KEY_RE}[[:space:]]*[^[:space:]].*$" <<<"$LIVE_CONTENT" \
          | sed -E 's|^.*workflows_ref:[[:space:]]*||; s|[[:space:]]+$||'
      # An extracted value that is EMPTY after unquoting is named rather than
      # dropped: `workflows_ref: ""` is a pin the rewrite cannot move either
      # (REF_RE needs ≥1 character), so filtering blanks out here would let it
      # slip past the assertion while `uses:` moved — the exact silent half-bump
      # this guard exists to catch. It is not a legal ref, so it fails loudly.
      } | sed -E "s|^['\"]||; s|['\"]\$||" \
        | sed -E 's|^$|(empty)|' | grep -vFx "$NEW_SHA" | sort -u
    )
    if [[ -n "$STALE_PINS" ]]; then
      # Sanitize before echoing: these values come from a caller file, and the
      # run logs of this public repo are a workflow-command sink. `tr` collapses
      # the newline join but not a carriage return, so a value carrying `\r::`
      # could inject a command of its own; `::` is neutralized for the same
      # reason. (The value itself is a ref of THIS public repo, so there is
      # nothing private to redact — only a control character to defang.)
      SAFE_PINS=$(tr -d '\r' <<<"$STALE_PINS" | sed -E 's|::|:|g' | tr '\n' ' ' | sed -E 's|[[:space:]]+$||')
      echo "::warning::${REPO}: ${FILE} still pins github-workflows at ${SAFE_PINS} after the rewrite (expected ${NEW_SHA}) — failing repo to avoid a half-bumped caller"
      return 1
    fi

    # Already fully pinned → the rewrite is a no-op → nothing to do for this file.
    # Comparing the rewritten content to the original (rather than grepping for
    # NEW_SHA appearing *anywhere*) also repairs a half-bumped file: if a prior
    # run left one of two refs at NEW_SHA and the other stale, the content still
    # differs here, so the file is re-staged and repaired instead of skipped.
    if [[ "$NEW_CONTENT" == "$OLD_CONTENT" ]]; then
      echo "${REPO}: ${FILE} already at ${SHORT} — skipping"
      continue
    fi

    # Collect the label ONLY now that the file is confirmed staged. Labels from
    # entries that were skipped (missing / already-pinned) must not land on the
    # repo's real bump PR — a stray blocking label (e.g. `do-not-merge`) on a
    # skipped entry would else be applied to the actual bump.
    [[ -n "$LABEL" ]] && LABELS+=("$LABEL")

    # `$(...)` capture above (base64 -d, then sed) strips the file's trailing
    # newline, so printf '%s\n' restores exactly one — otherwise the committed
    # caller loses its EOF newline and trips the receiver repo's formatter
    # (oxfmt/prettier both require a trailing newline).
    PEND_FILE+=("$FILE")
    PEND_CONTENT+=("$(printf '%s\n' "$NEW_CONTENT" | base64 | tr -d '\n')")
  done

  # Nothing to bump for this repo → clean skip: no branch churn, no PR.
  if (( ${#PEND_FILE[@]} == 0 )); then
    return 0
  fi

  # Pass 2 — land EVERY staged file in ONE atomic commit via the Git Data API,
  # then point the stable bump branch at it. The previous per-file Contents PUT
  # loop committed files one at a time with no rollback, so a mid-sequence
  # failure left the earlier files already committed on the branch — and if an
  # open bump PR pointed at it, a partial-yet-mergeable bump (BE-3902). Building
  # one commit off the tip and moving the ref in a single step makes the bump
  # all-or-nothing: either every file lands or the branch is untouched.

  # 1. Create a blob for each staged file's new content.
  local -a TREE_ENTRIES=()
  local i BLOB_NEW
  for (( i = 0; i < ${#PEND_FILE[@]}; i++ )); do
    # Pass the base64 body on stdin (like the tree/commit calls below), not via
    # --field on argv — this keeps the content off /proc/<pid>/cmdline and out of
    # the ARG_MAX bound, and matches the surrounding Git Data API calls.
    BLOB_NEW=$(jq -n --arg content "${PEND_CONTENT[$i]}" \
        '{content: $content, encoding: "base64"}' \
      | gh api --method POST "repos/${REPO}/git/blobs" --input - --jq '.sha') || {
      echo "::warning::${REPO}: blob create for ${PEND_FILE[$i]} failed — skipping"
      return 1
    }
    # Callers are regular files (mode 100644 — the `.github/workflows/*.yml`
    # they pin from is never executable). `base_tree` below carries every OTHER
    # path in the repo unchanged, so the tree lists only the bumped files.
    TREE_ENTRIES+=("$(jq -n --arg path "${PEND_FILE[$i]}" --arg sha "$BLOB_NEW" \
      '{path: $path, mode: "100644", type: "blob", sha: $sha}')")
  done

  # 2. Build ONE tree off the default-branch tip carrying all staged blobs.
  #    `base_tree` must be a TREE SHA, not a commit SHA — the Create-a-tree API
  #    rejects a commit SHA (422), and a tree built with no valid `base_tree`
  #    would carry ONLY the bumped files, so merging its PR would delete every
  #    other path in the caller repo. `MAIN_SHA` is the tip *commit* SHA (still
  #    correct as the commit's parent below), so resolve its tree first.
  local MAIN_TREE_SHA
  MAIN_TREE_SHA=$(gh api "repos/${REPO}/git/commits/${MAIN_SHA}" --jq '.tree.sha') || {
    echo "::warning::${REPO}: cannot resolve base tree — skipping"
    return 1
  }
  local TREE_SHA
  TREE_SHA=$(printf '%s\n' "${TREE_ENTRIES[@]}" \
      | jq -s --arg base "$MAIN_TREE_SHA" '{base_tree: $base, tree: .}' \
      | gh api --method POST "repos/${REPO}/git/trees" --input - --jq '.sha') || {
    echo "::warning::${REPO}: tree create failed — skipping"
    return 1
  }

  # 3. Create ONE commit with that tree, parented on the tip so the PR is always
  #    a clean "bump to @SHORT" diff against the default branch (never stale
  #    commits accumulated across bumps, never drift if the caller's default
  #    branch moved since the last bump — BE-3882).
  local COMMIT_SHA
  COMMIT_SHA=$(jq -n \
      --arg msg "ci: bump ${TAG} to github-workflows@${SHORT}" \
      --arg tree "$TREE_SHA" --arg parent "$MAIN_SHA" \
      '{message: $msg, tree: $tree, parents: [$parent]}' \
      | gh api --method POST "repos/${REPO}/git/commits" --input - --jq '.sha') || {
    echo "::warning::${REPO}: commit create failed — skipping"
    return 1
  }

  # 4. Point the stable bump branch at the finished commit. Create it there if it
  #    is new; otherwise force it there so the diff is rebuilt from scratch (an
  #    open bump PR's branch, or residue from a prior run) rather than committed
  #    on top of the old bump (BE-3882). The ref moves in ONE step from its old
  #    state to the complete new commit — it never transiently sits at an empty
  #    or partial tree.
  if ! gh api --method POST "repos/${REPO}/git/refs" \
        --field ref="refs/heads/${BRANCH}" \
        --field sha="${COMMIT_SHA}" >/dev/null 2>&1; then
    gh api --method PATCH "repos/${REPO}/git/refs/heads/${BRANCH}" \
      --field sha="${COMMIT_SHA}" --field force=true >/dev/null 2>&1 || {
      echo "::warning::${REPO}: cannot point ${BRANCH} at the bump commit — skipping"
      return 1
    }
  fi

  # The title/body embed ${SHORT}. Build them once so the create and the
  # update-in-place paths post the identical, current text. The body is a single
  # line so the workflow parses it — a multi-line --body collapsed the step's
  # YAML in an earlier revision.
  local PR_TITLE PR_BODY
  PR_TITLE="ci: bump ${TAG} to github-workflows@${SHORT}"
  PR_BODY="Automatic SHA bump — \`${WORKFLOW_FILE}\` was updated in \`Comfy-Org/github-workflows\` at [\`${SHORT}\`](https://github.com/Comfy-Org/github-workflows/commit/${NEW_SHA})."
  # Note the identity wiring in the PR body when it was actually added this run
  # (skipped for a caller already wired — that gets a pure SHA bump). NB: keep
  # GitHub-Actions expression syntax out of this script — the caller entrypoint
  # interpolates those at parse time, not here.
  [[ -n "$WIRING_ADDED_ANY" ]] && PR_BODY="${PR_BODY} Also wires the cloud-code-bot review identity (\`bot_app_id\` → \`vars.APP_ID\`, plus the \`BOT_APP_PRIVATE_KEY\` secret) so the review posts under \`cloud-code-bot[bot]\` instead of \`github-actions[bot]\` — BE-1814."
  PR_BODY="${PR_BODY} _Opened by the \`bump-${TAG}-callers\` workflow._"

  # Reuse the one open bump PR for this branch if there is one: the branch push
  # above already refreshed its diff to the new SHA, so just refresh its
  # title/body. The stable head branch guarantees at most ONE open bump PR per
  # (repo, TAG) at any time — never open a second (BE-3882).
  #
  # `.[0].number // empty` (not a bare `.[0].number`, which prints the literal
  # `null` on an empty list and would send us down `gh pr edit null`). And
  # because `--head` matches by branch *name* across forks, exclude
  # cross-repository PRs (`isCrossRepository == false`): the branch name is now
  # predictable (`ci/bump-<tag>`), so an attacker could pre-open a fork PR on it
  # and have the bot stamp their PR with the official title/body instead of
  # bumping the real caller. Only the caller repo's own bump branch counts.
  local EXISTING_PR
  EXISTING_PR=$(gh pr list --repo "${REPO}" --head "${BRANCH}" --state open \
    --json number,isCrossRepository \
    --jq 'map(select(.isCrossRepository == false)) | .[0].number // empty' 2>/dev/null)
  if [[ -n "$EXISTING_PR" ]]; then
    if gh pr edit "${EXISTING_PR}" --repo "${REPO}" \
        --title "${PR_TITLE}" --body "${PR_BODY}" >/dev/null 2>&1; then
      echo "${REPO}: PR #${EXISTING_PR} updated to ${SHORT}"
    else
      echo "::warning::${REPO}: failed to update open PR #${EXISTING_PR}"
      return 1
    fi
    return 0
  fi

  # No open PR for this branch → open one (first bump, or the prior PR was
  # merged/closed — and its branch possibly auto-deleted — since the last run).
  # Apply every distinct non-empty label the repo's entries carried (they need
  # not agree; dedup so `gh pr create` isn't passed the same label twice).
  # Exact-match membership (not a `|${L}|` substring sentinel): GitHub label
  # names may themselves contain `|`, so a substring test could drop a distinct
  # label whose name is a substring of an already-seen one (e.g. `bug` vs `bug|ui`).
  local -a LABEL_ARGS=() SEEN_LABELS=()
  local L S DUP
  for L in ${LABELS[@]+"${LABELS[@]}"}; do
    DUP=0
    for S in ${SEEN_LABELS[@]+"${SEEN_LABELS[@]}"}; do
      [[ "$S" == "$L" ]] && { DUP=1; break; }
    done
    (( DUP )) && continue
    SEEN_LABELS+=("$L"); LABEL_ARGS+=(--label "$L")
  done
  if gh pr create \
    --repo "${REPO}" \
    --head "${BRANCH}" \
    --base "${DEFAULT_BRANCH}" \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" \
    "${LABEL_ARGS[@]}" 2>/dev/null; then
    echo "${REPO}: PR opened"
    return 0
  else
    # Reaching here means no open bump PR existed (the update-in-place path
    # above already handled that case), so a create failure is a real error
    # — auth, branch protection, an invalid label, a transient API fault — not
    # a benign "PR already exists". Fail the caller so it lands in FAILED and
    # the job reports the miss instead of a silent success.
    echo "::warning::${REPO}: PR create failed for ${BRANCH}"
    return 1
  fi
}

# Group the flat entry list by repo, preserving first-seen order, so each repo
# is bumped exactly once with ALL of its files (BE-3896). `|` can't appear in a
# repo name (it is the field delimiter), so it is a safe membership sentinel.
REPOS=()
SEEN_REPOS=""
for ENTRY in "${CALLERS[@]}"; do
  REPO="${ENTRY%%|*}"
  case "$SEEN_REPOS" in
    *"|${REPO}|"*) ;;
    *) REPOS+=("$REPO"); SEEN_REPOS="${SEEN_REPOS}|${REPO}|" ;;
  esac
done

FAILED=()
for REPO in "${REPOS[@]}"; do
  # Collect this repo's entries (in their original order) and bump them together.
  ENTRIES=()
  for ENTRY in "${CALLERS[@]}"; do
    [[ "${ENTRY%%|*}" == "$REPO" ]] && ENTRIES+=("$ENTRY")
  done
  bump_repo "$REPO" "${ENTRIES[@]}" || FAILED+=("$REPO")
done

if (( ${#FAILED[@]} )); then
  printf '::error::bump failed for %d repo(s): %s\n' "${#FAILED[@]}" "${FAILED[*]}"
  exit 1
fi
echo "${TAG} bump complete for all callers."
