#!/usr/bin/env bash
#
# Generalized caller SHA-bumper for the reusable workflows in this repo.
#
# When a reusable workflow (e.g. cursor-review.yml or agents-md-integrity.yml)
# is updated on main, this opens a SHA-bump PR in every repo that pins a caller
# against it. It is fleet-agnostic: the thin workflow entrypoints (the
# bump-*-callers.yml workflows — see the fleet table in this directory's
# README) invoke it with a different caller list, human tag, and
# reusable-workflow filename. There is ONE implementation so the fleets
# cannot drift apart (a forked copy is how other shared machinery in the org
# has rotted); the entrypoints differ only in their path-filter triggers and
# the parameters below.
#
# This repo is PUBLIC (both the workflow files and the Actions run logs are
# publicly viewable) and most callers are private, so caller names must never
# appear in a committed file or in the logs. Each caller list lives in a
# repo-level Actions variable (config, not a credential — a variable, not a
# secret) as a JSON array of {"repo","file","label","wire_bot"} objects, and
# every repo name is `::add-mask::`ed out of the run logs before it is ever
# echoed.
#
# Required environment:
#   GH_TOKEN       Token with contents:write + pull-requests:write on the callers
#                  (the Cloud Code Bot app token generated by the entrypoint).
#   NEW_SHA        The github-workflows commit to pin callers to (github.sha).
#   CALLERS_JSON   The caller list (value of the fleet's Actions variable).
#   VAR_NAME       Name of that variable — used only in error messages.
#   TAG            Human tag for branch/commit/PR text (e.g. "cursor-review").
#   WORKFLOW_FILE  Reusable workflow filename referenced in the PR body.
# Optional:
#   ALLOW_EMPTY      "true" → an empty caller list is a clean no-op (a fleet that
#                    is seeded empty and grows). Default "false" → an empty/missing
#                    list is a hard error (a fleet that always has callers must
#                    never silently no-op — that would leave every caller un-bumped
#                    without anyone noticing).
#   WIRE_BOT_SCRIPT  Path to a helper that reads a caller's YAML on stdin and
#                    writes it back wired for some extra identity/config, idempotently
#                    (BE-1814's .github/cursor-review/wire-bot-identity.py). Only
#                    consulted for an entry whose `wire_bot` field is true; unset
#                    (the agents-md-integrity entrypoint never sets it) means no
#                    fleet here uses wiring, so a stray `wire_bot: true` in that
#                    fleet's variable is a harmless no-op with a warning, not a
#                    failure — this keeps the script itself cursor-review-agnostic.

# NOTE: deliberately no `set -e`. Each caller is bumped independently in
# bump_one(); a failure there returns non-zero and is downgraded to a per-repo
# warning so one bad repo cannot abort the whole fan-out. We still fail the job
# at the end if any repo failed.
set -uo pipefail

: "${NEW_SHA:?NEW_SHA is required}"
: "${VAR_NAME:?VAR_NAME is required}"
: "${TAG:?TAG is required}"
: "${WORKFLOW_FILE:?WORKFLOW_FILE is required}"
CALLERS_JSON="${CALLERS_JSON-}"
ALLOW_EMPTY="${ALLOW_EMPTY:-false}"
WIRE_BOT_SCRIPT="${WIRE_BOT_SCRIPT-}"

SHORT="${NEW_SHA:0:7}"
# Stable branch per (repo, TAG) — deliberately NOT SHA-stamped. A fixed head
# branch is what lets a subsequent bump reuse (and update in place) the one open
# bump PR instead of opening a fresh PR on every SHA (BE-3882). The SHA lives in
# the commit/title/body, not the branch name.
BRANCH="ci/bump-${TAG}"

STRIPPED="${CALLERS_JSON//[[:space:]]/}"

# Empty handling is fleet-specific. A fleet seeded empty (ALLOW_EMPTY=true)
# treats an empty/absent list as an expected clean no-op — its per-repo caller
# tickets add entries as callers land. Every other fleet keeps the original
# hard-fail so a silent no-op dispatcher (which would leave every caller
# un-bumped) is impossible.
if [[ "$ALLOW_EMPTY" == "true" ]] && { [[ -z "$STRIPPED" ]] || [[ "$STRIPPED" == "[]" ]]; }; then
  echo "${VAR_NAME} has no callers yet — nothing to bump for ${TAG}."
  exit 0
fi

# Load the caller list. Hard-fail loudly on a missing/empty/invalid value.
if [[ -z "$STRIPPED" ]]; then
  echo "::error::${VAR_NAME} variable is missing or empty. Seed it with the caller list — see this workflow's header comment for the update flow."
  exit 1
fi
if ! jq -e 'type == "array" and length > 0 and all(.[]; (.repo | type == "string" and . != "") and (.file | type == "string" and . != "") and (.wire_bot == null or (.wire_bot | type == "boolean")))' <<<"$CALLERS_JSON" >/dev/null 2>&1; then
  echo "::error::${VAR_NAME} is not a non-empty JSON array of {repo,file,label,wire_bot} objects (each needing a non-empty repo and file, and a boolean wire_bot if present). Fix the variable — see the workflow header."
  exit 1
fi

# Parse the JSON into repo|file|label|wire_bot tuples, and mask every repo name
# in the (publicly viewable) run logs BEFORE the loop that echoes it, so all
# per-repo output shows *** instead of a private repo name. jq's `//` treats
# both `false` and `null` as falsy, so an absent/false/null wire_bot all print
# the empty string here — exactly the "not flagged" case.
CALLERS=()
while IFS= read -r ENTRY; do
  echo "::add-mask::${ENTRY%%|*}"
  CALLERS+=("$ENTRY")
done < <(jq -r '.[] | "\(.repo)|\(.file)|\(.label // "")|\(.wire_bot // "")"' <<<"$CALLERS_JSON")

if (( ${#CALLERS[@]} == 0 )); then
  echo "::error::${VAR_NAME} parsed to zero callers — refusing to run a no-op dispatcher."
  exit 1
fi

# Bump ONE caller repo, committing EVERY file that repo pins onto a single
# stable bump branch. Called once per repo with that repo's entries, so a repo
# listed more than once in the caller variable (a monorepo pinning the reusable
# workflow from several workflow files) lands ALL its files on ONE branch/PR.
# Every external call is guarded, so a bad repo returns non-zero here (caught by
# the loop) instead of killing the run. A repo whose files are all missing or
# already pinned commits nothing and is a successful skip (`return 0`).
#
# Grouping by repo is load-bearing: all of a repo's files are built into ONE
# atomic commit (Git Data API) off the default-branch tip and the bump branch is
# moved to it in a single step, so the PR either bumps every file or none — never
# a partial-yet-mergeable bump. The earlier per-file Contents PUT loop committed
# files one at a time with no rollback, so a mid-sequence failure left the
# earlier files already committed on the branch (BE-3902); and before that a
# per-ENTRY branch reset discarded earlier commits so only the last file shipped
# (BE-3896). One commit for the whole repo closes both.
bump_repo() {
  local REPO="$1"; shift   # remaining args: this repo's "repo|file|label" entries

  local DEFAULT_BRANCH
  DEFAULT_BRANCH=$(gh api "repos/${REPO}" --jq '.default_branch') || {
    echo "::warning::${REPO}: cannot read repo metadata — skipping"
    return 1
  }

  # Resolve the default-branch tip ONCE, up front. Every Pass-1 fetch is pinned
  # to this immutable SHA (not the mutable `?ref=<branch>`), and Pass 2 uses the
  # same commit as the new commit's parent AND (via its resolved tree) as the
  # tree's `base_tree` — so the whole bump is built against one consistent
  # snapshot of the caller repo, never a moving tip. Reading the tip is a GET (no
  # branch churn), so it is safe before the all-skip early return.
  local MAIN_SHA
  MAIN_SHA=$(gh api "repos/${REPO}/git/refs/heads/${DEFAULT_BRANCH}" --jq '.object.sha') || {
    echo "::warning::${REPO}: cannot read ${DEFAULT_BRANCH} ref — skipping"
    return 1
  }

  # Pass 1 — stage every file that actually needs a bump WITHOUT writing
  # anything yet. This keeps the reset/commit path off entirely for a repo whose
  # files are all missing or already pinned (the old per-entry skips), so it
  # never resets a branch or opens a PR it doesn't need.
  local -a PEND_FILE=() PEND_CONTENT=() LABELS=()
  local WIRING_ADDED_ANY=""
  local ENTRY FILE LABEL WIRE_BOT FILE_ENC CURRENT OLD_CONTENT NEW_CONTENT
  for ENTRY in "$@"; do
    FILE=$(cut -d'|' -f2 <<<"$ENTRY")
    LABEL=$(cut -d'|' -f3 <<<"$ENTRY")
    WIRE_BOT=$(cut -d'|' -f4 <<<"$ENTRY")
    FILE_ENC="${FILE//\//%2F}"

    # De-duplicate by file: a repo listed twice for the SAME path (a structurally
    # valid config) must stage that file ONCE. A second PUT carrying the same
    # pre-bump blob `sha` would 409 — the first PUT already moved the blob — and
    # fail the whole repo even though the file was actually bumped. Fold the
    # duplicate entry's label into the set (it still applies to the one PR) but
    # do not re-stage the file.
    local SEEN_FILE=0 P
    for P in ${PEND_FILE[@]+"${PEND_FILE[@]}"}; do
      [[ "$P" == "$FILE" ]] && { SEEN_FILE=1; break; }
    done
    if (( SEEN_FILE )); then
      [[ -n "$LABEL" ]] && LABELS+=("$LABEL")
      continue
    fi

    # Fetch current file, pinned to the resolved tip. Distinguish a genuine 404
    # (this file is actually absent → an expected per-file skip) from ANY other
    # failure (auth, rate limit, 5xx, network). Treating a transient error as
    # "not found" and continuing would open a PR that silently OMITS this file
    # while the job still reports success — the partial-bump class this refactor
    # exists to kill (BE-3896). So a non-404 failure fails the whole repo.
    local ERRFILE RC
    ERRFILE=$(mktemp)
    CURRENT=$(gh api "repos/${REPO}/contents/${FILE_ENC}?ref=${MAIN_SHA}" 2>"$ERRFILE"); RC=$?
    if (( RC != 0 )); then
      if grep -qi 'HTTP 404' "$ERRFILE"; then
        echo "::warning::${REPO}: ${FILE} not found — skipping"
        rm -f "$ERRFILE"
        continue
      fi
      echo "::warning::${REPO}: ${FILE} fetch failed (HTTP error, not 404) — failing repo to avoid a partial bump"
      rm -f "$ERRFILE"
      return 1
    fi
    rm -f "$ERRFILE"

    OLD_CONTENT=$(jq -r '.content' <<<"$CURRENT" | base64 -d)

    # Rewrite the github-workflows pin(s) to NEW_SHA and normalize the stale
    # `# github-workflows#NN` pin comment. Anchor the 40-hex substitution to the
    # two known pin contexts — the `uses: …Comfy-Org/github-workflows…@<sha>`
    # line and agents-md-integrity's bare `workflows_ref: <sha>` line — so a
    # full-SHA pin of ANOTHER action in the same file (`actions/checkout@<sha>`,
    # the org's mandated practice) is never clobbered to github-workflows' SHA.
    # The comment rewrite is a no-op for callers that use a different comment
    # form (e.g. agents-md-integrity's `# v1`), so it is safe to share.
    NEW_CONTENT=$(sed -E "/github-workflows|workflows_ref/ s/[0-9a-f]{40}/${NEW_SHA}/g; s|# github-workflows#[0-9]+|# github-workflows main (${SHORT})|g" <<<"$OLD_CONTENT")

    # Wire an extra identity/config into this file when its entry is flagged
    # (BE-1814's cloud-code-bot review identity is the first user). Idempotent —
    # an already-wired caller comes back unchanged — so this only adds the
    # wiring to callers that don't have it yet, alongside the SHA bump. Folded
    # into the SAME content-equality check below (not a separate "grep for the
    # wired marker" skip) so a wiring-only change on an already-SHA-current
    # caller still stages the file instead of being short-circuited.
    if [[ -n "$WIRE_BOT" ]]; then
      if [[ -z "$WIRE_BOT_SCRIPT" ]]; then
        echo "::warning::${REPO}: ${FILE} flagged wire_bot but WIRE_BOT_SCRIPT is unset — bumping SHA only"
      else
        local WIRED
        if WIRED=$(python3 "$WIRE_BOT_SCRIPT" <<<"$NEW_CONTENT") && [[ -n "$WIRED" ]]; then
          [[ "$WIRED" != "$NEW_CONTENT" ]] && WIRING_ADDED_ANY=1
          NEW_CONTENT="$WIRED"
        else
          echo "::warning::${REPO}: ${FILE} bot-identity wiring failed — bumping SHA only"
        fi
      fi
    fi

    # Already fully pinned → the rewrite is a no-op → nothing to do for this file.
    # Comparing the rewritten content to the original (rather than grepping for
    # NEW_SHA appearing *anywhere*) also repairs a half-bumped file: if a prior
    # run left one of two refs at NEW_SHA and the other stale, the content still
    # differs here, so the file is re-staged and repaired instead of skipped.
    if [[ "$NEW_CONTENT" == "$OLD_CONTENT" ]]; then
      echo "${REPO}: ${FILE} already at ${SHORT} — skipping"
      continue
    fi

    # Collect the label ONLY now that the file is confirmed staged. Labels from
    # entries that were skipped (missing / already-pinned) must not land on the
    # repo's real bump PR — a stray blocking label (e.g. `do-not-merge`) on a
    # skipped entry would else be applied to the actual bump.
    [[ -n "$LABEL" ]] && LABELS+=("$LABEL")

    # `$(...)` capture above (base64 -d, then sed) strips the file's trailing
    # newline, so printf '%s\n' restores exactly one — otherwise the committed
    # caller loses its EOF newline and trips the receiver repo's formatter
    # (oxfmt/prettier both require a trailing newline).
    PEND_FILE+=("$FILE")
    PEND_CONTENT+=("$(printf '%s\n' "$NEW_CONTENT" | base64 | tr -d '\n')")
  done

  # Nothing to bump for this repo → clean skip: no branch churn, no PR.
  if (( ${#PEND_FILE[@]} == 0 )); then
    return 0
  fi

  # Pass 2 — land EVERY staged file in ONE atomic commit via the Git Data API,
  # then point the stable bump branch at it. The previous per-file Contents PUT
  # loop committed files one at a time with no rollback, so a mid-sequence
  # failure left the earlier files already committed on the branch — and if an
  # open bump PR pointed at it, a partial-yet-mergeable bump (BE-3902). Building
  # one commit off the tip and moving the ref in a single step makes the bump
  # all-or-nothing: either every file lands or the branch is untouched.

  # 1. Create a blob for each staged file's new content.
  local -a TREE_ENTRIES=()
  local i BLOB_NEW
  for (( i = 0; i < ${#PEND_FILE[@]}; i++ )); do
    # Pass the base64 body on stdin (like the tree/commit calls below), not via
    # --field on argv — this keeps the content off /proc/<pid>/cmdline and out of
    # the ARG_MAX bound, and matches the surrounding Git Data API calls.
    BLOB_NEW=$(jq -n --arg content "${PEND_CONTENT[$i]}" \
        '{content: $content, encoding: "base64"}' \
      | gh api --method POST "repos/${REPO}/git/blobs" --input - --jq '.sha') || {
      echo "::warning::${REPO}: blob create for ${PEND_FILE[$i]} failed — skipping"
      return 1
    }
    # Callers are regular files (mode 100644 — the `.github/workflows/*.yml`
    # they pin from is never executable). `base_tree` below carries every OTHER
    # path in the repo unchanged, so the tree lists only the bumped files.
    TREE_ENTRIES+=("$(jq -n --arg path "${PEND_FILE[$i]}" --arg sha "$BLOB_NEW" \
      '{path: $path, mode: "100644", type: "blob", sha: $sha}')")
  done

  # 2. Build ONE tree off the default-branch tip carrying all staged blobs.
  #    `base_tree` must be a TREE SHA, not a commit SHA — the Create-a-tree API
  #    rejects a commit SHA (422), and a tree built with no valid `base_tree`
  #    would carry ONLY the bumped files, so merging its PR would delete every
  #    other path in the caller repo. `MAIN_SHA` is the tip *commit* SHA (still
  #    correct as the commit's parent below), so resolve its tree first.
  local MAIN_TREE_SHA
  MAIN_TREE_SHA=$(gh api "repos/${REPO}/git/commits/${MAIN_SHA}" --jq '.tree.sha') || {
    echo "::warning::${REPO}: cannot resolve base tree — skipping"
    return 1
  }
  local TREE_SHA
  TREE_SHA=$(printf '%s\n' "${TREE_ENTRIES[@]}" \
      | jq -s --arg base "$MAIN_TREE_SHA" '{base_tree: $base, tree: .}' \
      | gh api --method POST "repos/${REPO}/git/trees" --input - --jq '.sha') || {
    echo "::warning::${REPO}: tree create failed — skipping"
    return 1
  }

  # 3. Create ONE commit with that tree, parented on the tip so the PR is always
  #    a clean "bump to @SHORT" diff against the default branch (never stale
  #    commits accumulated across bumps, never drift if the caller's default
  #    branch moved since the last bump — BE-3882).
  local COMMIT_SHA
  COMMIT_SHA=$(jq -n \
      --arg msg "ci: bump ${TAG} to github-workflows@${SHORT}" \
      --arg tree "$TREE_SHA" --arg parent "$MAIN_SHA" \
      '{message: $msg, tree: $tree, parents: [$parent]}' \
      | gh api --method POST "repos/${REPO}/git/commits" --input - --jq '.sha') || {
    echo "::warning::${REPO}: commit create failed — skipping"
    return 1
  }

  # 4. Point the stable bump branch at the finished commit. Create it there if it
  #    is new; otherwise force it there so the diff is rebuilt from scratch (an
  #    open bump PR's branch, or residue from a prior run) rather than committed
  #    on top of the old bump (BE-3882). The ref moves in ONE step from its old
  #    state to the complete new commit — it never transiently sits at an empty
  #    or partial tree.
  if ! gh api --method POST "repos/${REPO}/git/refs" \
        --field ref="refs/heads/${BRANCH}" \
        --field sha="${COMMIT_SHA}" >/dev/null 2>&1; then
    gh api --method PATCH "repos/${REPO}/git/refs/heads/${BRANCH}" \
      --field sha="${COMMIT_SHA}" --field force=true >/dev/null 2>&1 || {
      echo "::warning::${REPO}: cannot point ${BRANCH} at the bump commit — skipping"
      return 1
    }
  fi

  # The title/body embed ${SHORT}. Build them once so the create and the
  # update-in-place paths post the identical, current text. The body is a single
  # line so the workflow parses it — a multi-line --body collapsed the step's
  # YAML in an earlier revision.
  local PR_TITLE PR_BODY
  PR_TITLE="ci: bump ${TAG} to github-workflows@${SHORT}"
  PR_BODY="Automatic SHA bump — \`${WORKFLOW_FILE}\` was updated in \`Comfy-Org/github-workflows\` at [\`${SHORT}\`](https://github.com/Comfy-Org/github-workflows/commit/${NEW_SHA})."
  # Note the identity wiring in the PR body when it was actually added this run
  # (skipped for a caller already wired — that gets a pure SHA bump). NB: keep
  # GitHub-Actions expression syntax out of this script — the caller entrypoint
  # interpolates those at parse time, not here.
  [[ -n "$WIRING_ADDED_ANY" ]] && PR_BODY="${PR_BODY} Also wires the cloud-code-bot review identity (\`bot_app_id\` → \`vars.APP_ID\`, plus the \`BOT_APP_PRIVATE_KEY\` secret) so the review posts under \`cloud-code-bot[bot]\` instead of \`github-actions[bot]\` — BE-1814."
  PR_BODY="${PR_BODY} _Opened by the \`bump-${TAG}-callers\` workflow._"

  # Reuse the one open bump PR for this branch if there is one: the branch push
  # above already refreshed its diff to the new SHA, so just refresh its
  # title/body. The stable head branch guarantees at most ONE open bump PR per
  # (repo, TAG) at any time — never open a second (BE-3882).
  #
  # `.[0].number // empty` (not a bare `.[0].number`, which prints the literal
  # `null` on an empty list and would send us down `gh pr edit null`). And
  # because `--head` matches by branch *name* across forks, exclude
  # cross-repository PRs (`isCrossRepository == false`): the branch name is now
  # predictable (`ci/bump-<tag>`), so an attacker could pre-open a fork PR on it
  # and have the bot stamp their PR with the official title/body instead of
  # bumping the real caller. Only the caller repo's own bump branch counts.
  local EXISTING_PR
  EXISTING_PR=$(gh pr list --repo "${REPO}" --head "${BRANCH}" --state open \
    --json number,isCrossRepository \
    --jq 'map(select(.isCrossRepository == false)) | .[0].number // empty' 2>/dev/null)
  if [[ -n "$EXISTING_PR" ]]; then
    if gh pr edit "${EXISTING_PR}" --repo "${REPO}" \
        --title "${PR_TITLE}" --body "${PR_BODY}" >/dev/null 2>&1; then
      echo "${REPO}: PR #${EXISTING_PR} updated to ${SHORT}"
    else
      echo "::warning::${REPO}: failed to update open PR #${EXISTING_PR}"
      return 1
    fi
    return 0
  fi

  # No open PR for this branch → open one (first bump, or the prior PR was
  # merged/closed — and its branch possibly auto-deleted — since the last run).
  # Apply every distinct non-empty label the repo's entries carried (they need
  # not agree; dedup so `gh pr create` isn't passed the same label twice).
  # Exact-match membership (not a `|${L}|` substring sentinel): GitHub label
  # names may themselves contain `|`, so a substring test could drop a distinct
  # label whose name is a substring of an already-seen one (e.g. `bug` vs `bug|ui`).
  local -a LABEL_ARGS=() SEEN_LABELS=()
  local L S DUP
  for L in ${LABELS[@]+"${LABELS[@]}"}; do
    DUP=0
    for S in ${SEEN_LABELS[@]+"${SEEN_LABELS[@]}"}; do
      [[ "$S" == "$L" ]] && { DUP=1; break; }
    done
    (( DUP )) && continue
    SEEN_LABELS+=("$L"); LABEL_ARGS+=(--label "$L")
  done
  if gh pr create \
    --repo "${REPO}" \
    --head "${BRANCH}" \
    --base "${DEFAULT_BRANCH}" \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" \
    "${LABEL_ARGS[@]}" 2>/dev/null; then
    echo "${REPO}: PR opened"
    return 0
  else
    # Reaching here means no open bump PR existed (the update-in-place path
    # above already handled that case), so a create failure is a real error
    # — auth, branch protection, an invalid label, a transient API fault — not
    # a benign "PR already exists". Fail the caller so it lands in FAILED and
    # the job reports the miss instead of a silent success.
    echo "::warning::${REPO}: PR create failed for ${BRANCH}"
    return 1
  fi
}

# Group the flat entry list by repo, preserving first-seen order, so each repo
# is bumped exactly once with ALL of its files (BE-3896). `|` can't appear in a
# repo name (it is the field delimiter), so it is a safe membership sentinel.
REPOS=()
SEEN_REPOS=""
for ENTRY in "${CALLERS[@]}"; do
  REPO="${ENTRY%%|*}"
  case "$SEEN_REPOS" in
    *"|${REPO}|"*) ;;
    *) REPOS+=("$REPO"); SEEN_REPOS="${SEEN_REPOS}|${REPO}|" ;;
  esac
done

FAILED=()
for REPO in "${REPOS[@]}"; do
  # Collect this repo's entries (in their original order) and bump them together.
  ENTRIES=()
  for ENTRY in "${CALLERS[@]}"; do
    [[ "${ENTRY%%|*}" == "$REPO" ]] && ENTRIES+=("$ENTRY")
  done
  bump_repo "$REPO" "${ENTRIES[@]}" || FAILED+=("$REPO")
done

if (( ${#FAILED[@]} )); then
  printf '::error::bump failed for %d repo(s): %s\n' "${#FAILED[@]}" "${FAILED[*]}"
  exit 1
fi
echo "${TAG} bump complete for all callers."
